/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetLockRouteImport } from './routes/reset-lock'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSosRouteImport } from './routes/app.sos'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppLocationRouteImport } from './routes/app.location'
import { Route as AppLoanRouteImport } from './routes/app.loan'
import { Route as AppIncomeRouteImport } from './routes/app.income'
import { Route as AppGigscoreRouteImport } from './routes/app.gigscore'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppChargingRouteImport } from './routes/app.charging'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AppSchemesIndexRouteImport } from './routes/app.schemes.index'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const ResetLockRoute = ResetLockRouteImport.update({
  id: '/reset-lock',
  path: '/reset-lock',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSosRoute = AppSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationRoute = AppLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => AppRoute,
} as any)
const AppLoanRoute = AppLoanRouteImport.update({
  id: '/loan',
  path: '/loan',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRoute = AppIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AppRoute,
} as any)
const AppGigscoreRoute = AppGigscoreRouteImport.update({
  id: '/gigscore',
  path: '/gigscore',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppChargingRoute = AppChargingRouteImport.update({
  id: '/charging',
  path: '/charging',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSchemesIndexRoute = AppSchemesIndexRouteImport.update({
  id: '/schemes/',
  path: '/schemes/',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-lock': typeof ResetLockRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/charging': typeof AppChargingRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/gigscore': typeof AppGigscoreRoute
  '/app/income': typeof AppIncomeRoute
  '/app/loan': typeof AppLoanRoute
  '/app/location': typeof AppLocationRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sos': typeof AppSosRoute
  '/app/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/schemes/': typeof AppSchemesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-lock': typeof ResetLockRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/charging': typeof AppChargingRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/gigscore': typeof AppGigscoreRoute
  '/app/income': typeof AppIncomeRoute
  '/app/loan': typeof AppLoanRoute
  '/app/location': typeof AppLocationRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sos': typeof AppSosRoute
  '/app': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/schemes': typeof AppSchemesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-lock': typeof ResetLockRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/charging': typeof AppChargingRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/gigscore': typeof AppGigscoreRoute
  '/app/income': typeof AppIncomeRoute
  '/app/loan': typeof AppLoanRoute
  '/app/location': typeof AppLocationRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sos': typeof AppSosRoute
  '/app/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/schemes/': typeof AppSchemesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/mcp'
    | '/onboarding'
    | '/reset-lock'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/charging'
    | '/app/documents'
    | '/app/gigscore'
    | '/app/income'
    | '/app/loan'
    | '/app/location'
    | '/app/profile'
    | '/app/settings'
    | '/app/sos'
    | '/app/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/schemes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/mcp'
    | '/onboarding'
    | '/reset-lock'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/charging'
    | '/app/documents'
    | '/app/gigscore'
    | '/app/income'
    | '/app/loan'
    | '/app/location'
    | '/app/profile'
    | '/app/settings'
    | '/app/sos'
    | '/app'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/schemes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/mcp'
    | '/onboarding'
    | '/reset-lock'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/charging'
    | '/app/documents'
    | '/app/gigscore'
    | '/app/income'
    | '/app/loan'
    | '/app/location'
    | '/app/profile'
    | '/app/settings'
    | '/app/sos'
    | '/app/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/schemes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetLockRoute: typeof ResetLockRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-lock': {
      id: '/reset-lock'
      path: '/reset-lock'
      fullPath: '/reset-lock'
      preLoaderRoute: typeof ResetLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sos': {
      id: '/app/sos'
      path: '/sos'
      fullPath: '/app/sos'
      preLoaderRoute: typeof AppSosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/location': {
      id: '/app/location'
      path: '/location'
      fullPath: '/app/location'
      preLoaderRoute: typeof AppLocationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/loan': {
      id: '/app/loan'
      path: '/loan'
      fullPath: '/app/loan'
      preLoaderRoute: typeof AppLoanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/income': {
      id: '/app/income'
      path: '/income'
      fullPath: '/app/income'
      preLoaderRoute: typeof AppIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gigscore': {
      id: '/app/gigscore'
      path: '/gigscore'
      fullPath: '/app/gigscore'
      preLoaderRoute: typeof AppGigscoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/charging': {
      id: '/app/charging'
      path: '/charging'
      fullPath: '/app/charging'
      preLoaderRoute: typeof AppChargingRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/schemes/': {
      id: '/app/schemes/'
      path: '/schemes'
      fullPath: '/app/schemes/'
      preLoaderRoute: typeof AppSchemesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppChargingRoute: typeof AppChargingRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppGigscoreRoute: typeof AppGigscoreRoute
  AppIncomeRoute: typeof AppIncomeRoute
  AppLoanRoute: typeof AppLoanRoute
  AppLocationRoute: typeof AppLocationRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSosRoute: typeof AppSosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSchemesIndexRoute: typeof AppSchemesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChargingRoute: AppChargingRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppGigscoreRoute: AppGigscoreRoute,
  AppIncomeRoute: AppIncomeRoute,
  AppLoanRoute: AppLoanRoute,
  AppLocationRoute: AppLocationRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSosRoute: AppSosRoute,
  AppIndexRoute: AppIndexRoute,
  AppSchemesIndexRoute: AppSchemesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  ResetLockRoute: ResetLockRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
